// <auto-generated />
using Api.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210224819_FourMigrations_1")]
    partial class FourMigrations_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.BrandsCars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BrandsCars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ford"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hiunday"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mazda"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kia"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chevrolet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
